### ISSUE TITLE
username and password should go into some other file

### ISSUE THREAD

**Issue by tonythomas01** [joyceg/Internship-form#1]
You cannot have it in the main receiver file.  You can require_once the settings file to get the values. http://php.net/manual/en/function.require-once.php

**Comment by joyceg** [comment]
A new file has been create to store these authentication details.
Closing the issue.

**Comment by tonythomas01** [comment]
Before closing it, add the commit id too here, or the link so that other people can track how it was fixed. Thanks

**Comment by joyceg** [comment]
commit id:https://github.com/joyceg/Internship-form/commit/e96e1a4535c8ac40005495b8193d3a69b4473cc0
