### ISSUE TITLE
Create a reg_id SERIAL UNIQUE PRIMARY KEY

### ISSUE THREAD

**Issue by tonythomas01** [joyceg/Internship-form#10]
It would be better than making the ROLL Number as PRIMARY KEY

**Comment by joyceg** [comment]
Roll number will be unique,right?

**Comment by tonythomas01** [comment]
no - its not easy to handle a PRIMARY KEY with that size which includes chars and numbers. A student can apply for multiple internships. Also, try to show up an INTERNSHIP_ID on the top of the form when printing.

**Comment by joyceg** [comment]
solved
https://github.com/joyceg/Internship-form/commit/b260560020d47b734d97972c4c36211cdd383f8f
