### ISSUE TITLE
php should firstly check if table exist, if not - create it 

### ISSUE THREAD

**Issue by tonythomas01** [joyceg/Internship-form#2]
You should use something like: 
$createQuery = CREATE TABLE IF NOT EXIST (     ); 
in the first few lines, so that you need not manually create the table everytime you deploy it.

**Comment by joyceg** [comment]
solved:
id:https://github.com/joyceg/Internship-form/commit/d18c4a1ca9cdf96760839eb5a99ee082dda7c685

**Comment by joyceg** [comment]
closing issue:
id:https://github.com/joyceg/Internship-form/commit/111ef93e47856dac8f1239cd3c1176fa0285f14a
