### ISSUE TITLE
Avoid debugging text in the php code

### ISSUE THREAD

**Issue by tonythomas01** [joyceg/Internship-form#6]
https://github.com/joyceg/Internship-form/blob/master/receiver.php#L11 should not be there in a to-be deployed website

**Comment by joyceg** [comment]
What is the issue here?

**Comment by tonythomas01** [comment]
Read the subject and try to understand the bug. Even the line number is given.

**Comment by joyceg** [comment]
closing
https://github.com/joyceg/Internship-form/commit/41fa75c25af4dcb0a0aa847709eb97dfe6cba325
